### ISSUE TITLE
Social/share buttons

### ISSUE THREAD

**Issue by martiis** [DashboardHub/DashboardHub.github.io#18]
Hi @eddiejaoude, nice blog but it would be even better that every article had atleast Facebook and Twitter share buttons :)

**Comment by eddiejaoude** [comment]
Thanks @martiis for the feedback. It is a great idea!! I will look into it :)

**Comment by eddiejaoude** [comment]
Good example of how to achieve Social Share buttons in **Jeykll** http://codingtips.kanishkkunal.in/share-buttons-jekyll/

**Comment by eddiejaoude** [comment]
![screenshot 2015-05-28 10 43 13](https://cloud.githubusercontent.com/assets/624760/7857222/ba9ae422-0526-11e5-9402-4a1155b34b72.png)

**Comment by eddiejaoude** [comment]
![screenshot 2015-05-28 10 45 31](https://cloud.githubusercontent.com/assets/624760/7857240/c2306b62-0526-11e5-9a19-746fa280e779.png)

**Comment by eddiejaoude** [comment]
@martiis thanks again for the idea. Now it is done & implemented :smile:

**Comment by martiis** [comment]
hehe :D
