### ISSUE TITLE
Why you should release your project as open source

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/DashboardHub.github.io#26]
Pros:
- You will get better developers & better code base 
- Easier to build a community / eco system
- Free marketing
- Extra pair of eyes on the code base
  - Code review
  - Comments / Suggestions
- Vet potential developers who have already been involved in your project from the community 
  - Need more developers / tech help and advice - you now already have a pool of resources who are interested in your project
- Helps working faster, doesn't matter if competitors see your work / ideas, by the time they get there, you have moved on already :wink: 

Cons:
- Competitors can see your work & future ideas

Recommendations:
- If planning to Open Source your work, do it from the beginning - must easier

**Comment by andrew-cunliffe** [comment]
Just a few initial thoughts and previous discussions I have had, there are more points I'm sure so will add when I remember them...

### Pros:
- Transparency of work, you can't hide some port sending secret data, or collecting data it should not be.
- A world of experience, generating ideas and finding defects you may not even consider to be defects.
- Great for Libraries that maybe shared / consumed by many people and as such will become more flexible.
- Accuracy of work, simple things like a typo are exposed and someone is likely to pick it up for you.
- Advertising, even if you are not going to have load of people flocking to help you its another way people might find you.
- Common practices, using open source technologies and tools means you are more likely to use the latest and most refined ways of building software (branching, tagging, issue management etc)

### Cons:
- Crown Jewels, if you are building a centralised solution like an API you probably don't want others to interfere without having approved them first. Also if you have some great idea on your backlog someone might see this and build it before you, this can destroy a small business.
- Change of path, having many people looking at what you are doing can become a distraction leading you down a different path or building something you didn't want to build (could argue this is good however).
- Exposure (again can be good but...), everyone is a critic you may well be a great developer but if the wrong people get involved they could give you a bad name.
- Being prepared, open source requires a different mantra you need to be well organised and be able to manage both the community and your work loads.

### Final Note

You may choose to keep work private, but by following Open Source Technologies and Techniques you are never far away from making the final leap and opening your code base to the public, while it is best to do this from Day 1, sometimes you need to take small steps and using GitHub as a private repository is a great first step.
