### ISSUE TITLE
User feedback with DoorBell.io

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/DashboardHub.github.io#38]
Topics:
- Benefit of feedback
- The ease of DoorBell.io

**Comment by eddiejaoude** [comment]
User feedback is as useful as a **Pull Request**, why not make the feedback as simple as a developer creating a PR

**Comment by eddiejaoude** [comment]
Put live, but needs reviewing.

**Comment by manavo** [comment]
Thanks for the awesome write up @eddiejaoude! :+1:

**Comment by eddiejaoude** [comment]
No problem :). 

Does the Doorbell team plan to release more of it as Open Source in the future?

**Comment by manavo** [comment]
Would love to, but not sure yet! Any more SDKs would probably be open sourced. Would love to do an SDK for Windows mobile apps too, or maybe Mac/OSX apps.

The Javascript/web SDK is quite tightly integrated into Doorbell itself, so probably not a good open source candidate.

Definitely hoping to find more things to open source though!

**Comment by eddiejaoude** [comment]
> Definitely hoping to find more things to open source though!

:+1: 

You can tell I am a keen on Open Source, especially as we are Open Sourcing all of DashboardHub.

**Comment by manavo** [comment]
Yep, noticed that all of DashboardHub is open source. Awesome move on your part!

Is the model something like https://getsentry.com/welcome/ then? Free to self host, or you can pay a bit to get it hosted by you guys?

**Comment by eddiejaoude** [comment]
Yeah almost, our hosted part is still free for Open Source projects, but will be a small fee for private projects.

**Comment by manavo** [comment]
That's an awesome model I think. Free for open source, charge for private. It has definitely worked well for tons of companies (like Travis CI, Coveralls.io, etc)!

**Comment by eddiejaoude** [comment]
Yeah exactly! And I love those companies! :wink: 

> :speech_balloon:  DashboardHub .... I want to be like one of those when I grow up! :smile:

**Comment by manavo** [comment]
And I bet it will be like one of them in no time! :+1:
