### ISSUE TITLE
Great tools / libraries that DashboardHub use

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/DashboardHub.github.io#39]

**Comment by simoncasey** [comment]
- github (obvs)
- travis
- appear.in
- doorbell.io
- zoho
- github pages / jekyll
- gitter.im
- digital ocean
- dokku
- spring boot
- jitpack.io
- intellij idea
- json-server / jsonplaceholder
- wiremock

**Comment by eddiejaoude** [comment]
- symfony
- doctrine
- git
- phpstorm
- composer
- mysql
- elasticsearch

---

Sections:
- Code
- Comms
- DevOPs
